services:
  opensearch:
    image: opensearchproject/opensearch:2.14.0
    platform: linux/arm64
    environment:
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
      - plugins.security.disabled=true
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - http.port=9200
      - network.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch-data:/usr/share/opensearch/data

  dashboards:
    image: opensearchproject/opensearch-dashboards:2.14.0
    platform: linux/arm64
    environment:
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]   # ← JSON配列に修正（ダブルクォート）
      - SERVER_HOST=0.0.0.0                            # ← 念のため待受を明示
      - SERVER_PORT=5601
    ports:
      - "5601:5601"
    depends_on:
      - opensearch

volumes:
  opensearch-data:
